# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import echoserver_pb2 as echoserver__pb2


class EchoServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Echo = channel.unary_unary(
        '/EchoServer/Echo',
        request_serializer=echoserver__pb2.EchoRequest.SerializeToString,
        response_deserializer=echoserver__pb2.EchoResponse.FromString,
        )


class EchoServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Echo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EchoServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Echo': grpc.unary_unary_rpc_method_handler(
          servicer.Echo,
          request_deserializer=echoserver__pb2.EchoRequest.FromString,
          response_serializer=echoserver__pb2.EchoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'EchoServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
